spring.application.name=helloSteve

spring.datasource.url=jdbc:h2:mem:helloSteve
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.profiles.active=dev

# Automatically create database tables from JPA entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console at http://localhost:8080/h2-console
spring.h2.console.enabled=true