services:
  # --- Backend Service ---
  backend:
    build:
      context: ./helloSteve
      dockerfile: Dockerfile
    container_name: java-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

  # --- Frontend Service ---
  frontend:
    build:
      context: ./hiworld
      dockerfile: Dockerfile
    container_name: hiworld
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
