services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./helloSteve
    plan: free
    healthCheckPath: /actuator/health

  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: ./hiworld
